version: "3.7"

services:
  genieacs-cwmp:
    build:
      context: .
      dockerfile: ./dockerfiles/genieacs-cwmp.dockerfile
    ports:
      - "7547:7547"
    networks:
      - "genie-network"
    depends_on:
      - mongo_db
    restart: always
    environment:
      - GENIEACS_UI_JWT_SECRET=changeme
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo_db/genieacs

  genieacs-nbi:
    build:
      context: .
      dockerfile: ./dockerfiles/genieacs-nbi.dockerfile
    ports:
      - "7557:7557"
    networks:
      - "genie-network"
    depends_on:
      - mongo_db
    restart: always
    environment:
      - GENIEACS_UI_JWT_SECRET=changeme
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo_db/genieacs

  genieacs-fs:
    build:
      context: .
      dockerfile: ./dockerfiles/genieacs-fs.dockerfile
    ports:
      - "7567:7567"
    networks:
      - "genie-network"
    depends_on:
      - mongo_db
    restart: always
    environment:
      - GENIEACS_UI_JWT_SECRET=changeme
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo_db/genieacs

  genieacs-ui:
    build:
      context: .
      dockerfile: ./dockerfiles/genieacs-ui.dockerfile
    ports:
      - "3000:3000"
    networks:
      - "genie-network"
    depends_on:
      - mongo_db
    restart: always
    environment:
      - GENIEACS_UI_JWT_SECRET=changeme
      - GENIEACS_MONGODB_CONNECTION_URL=mongodb://mongo_db/genieacs

  mongo_db:
    image: mongo:4.4
    restart: always
    expose:
      - 27017
    networks:
      - genie-network

networks:
  genie-network:
    name: "genie-network"
